name = "MultiAssayExperiments"
uuid = "c9137f73-29f3-4436-b9da-846274f1d332"
authors = ["Aaron Lun <lun.aaron@gene.com>"]
version = "0.1.0"

[deps]
SummarizedExperiments = "b04b66ec-f619-4ebf-810e-cf5ccc546695"
