name = "MultiAssayExperiments"
uuid = "c9137f73-29f3-4436-b9da-846274f1d332"
authors = ["LTLA <infinite.monkeys.with.keyboards@gmail.com>"]
version = "0.2.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
SummarizedExperiments = "b04b66ec-f619-4ebf-810e-cf5ccc546695"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DataFrames = "1"
DataStructures = "0.18"
SummarizedExperiments = "0.2"
Reexport = "1"
julia = "1"
